title: Kyle Gordy
email: kyle@kgordy.com
description: >-
  I'm a freelance UI designer and front-end web developer working remotely.

# Build Settings
markdown: kramdown
sass:
  sass_dir: assets/_sass
  style: compressed

# Compress HTML Options
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: false
  blanklines: false

plugins:
  - jekyll-redirect-from

collections:
  work:
    output: true
    permalink: /work/:path/

# Links to include in header/footer
navigation:
  - title: Work
    url: /
  - title: About
    url: /about
  - title: contact
    url: /contact
